package com.zhen.base.domain.system;

import java.io.Serializable;

public class Bch implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BANK_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bankCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_LEGAL_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchLegalCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_DESC
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_FINC_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchFincCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_LEVEL
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_FAR_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchFarCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_ACCT_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchAcctCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_VM_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchVmCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_CONT_USR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchContUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_CONT_TEL
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchContTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_ADDR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_ZIP
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_TEMP_ACCT_NO
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchTempAcctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_STATUS
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.BCH_LOAN_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String bchLoanInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.LAST_CHG_DT
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String lastChgDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.LAST_CHG_USR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String lastChgUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.ZHXT_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String zhxtInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_BCH.OL_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private String olInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table S_BCH
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_CDE
     *
     * @return the value of S_BCH.BCH_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchCde() {
        return bchCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_CDE
     *
     * @param bchCde the value for S_BCH.BCH_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchCde(String bchCde) {
        this.bchCde = bchCde == null ? null : bchCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BANK_CDE
     *
     * @return the value of S_BCH.BANK_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBankCde() {
        return bankCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BANK_CDE
     *
     * @param bankCde the value for S_BCH.BANK_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBankCde(String bankCde) {
        this.bankCde = bankCde == null ? null : bankCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_LEGAL_CDE
     *
     * @return the value of S_BCH.BCH_LEGAL_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchLegalCde() {
        return bchLegalCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_LEGAL_CDE
     *
     * @param bchLegalCde the value for S_BCH.BCH_LEGAL_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchLegalCde(String bchLegalCde) {
        this.bchLegalCde = bchLegalCde == null ? null : bchLegalCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_DESC
     *
     * @return the value of S_BCH.BCH_DESC
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchDesc() {
        return bchDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_DESC
     *
     * @param bchDesc the value for S_BCH.BCH_DESC
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchDesc(String bchDesc) {
        this.bchDesc = bchDesc == null ? null : bchDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_FINC_CDE
     *
     * @return the value of S_BCH.BCH_FINC_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchFincCde() {
        return bchFincCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_FINC_CDE
     *
     * @param bchFincCde the value for S_BCH.BCH_FINC_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchFincCde(String bchFincCde) {
        this.bchFincCde = bchFincCde == null ? null : bchFincCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_LEVEL
     *
     * @return the value of S_BCH.BCH_LEVEL
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchLevel() {
        return bchLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_LEVEL
     *
     * @param bchLevel the value for S_BCH.BCH_LEVEL
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchLevel(String bchLevel) {
        this.bchLevel = bchLevel == null ? null : bchLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_FAR_CDE
     *
     * @return the value of S_BCH.BCH_FAR_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchFarCde() {
        return bchFarCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_FAR_CDE
     *
     * @param bchFarCde the value for S_BCH.BCH_FAR_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchFarCde(String bchFarCde) {
        this.bchFarCde = bchFarCde == null ? null : bchFarCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_ACCT_CDE
     *
     * @return the value of S_BCH.BCH_ACCT_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchAcctCde() {
        return bchAcctCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_ACCT_CDE
     *
     * @param bchAcctCde the value for S_BCH.BCH_ACCT_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchAcctCde(String bchAcctCde) {
        this.bchAcctCde = bchAcctCde == null ? null : bchAcctCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_VM_CDE
     *
     * @return the value of S_BCH.BCH_VM_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchVmCde() {
        return bchVmCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_VM_CDE
     *
     * @param bchVmCde the value for S_BCH.BCH_VM_CDE
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchVmCde(String bchVmCde) {
        this.bchVmCde = bchVmCde == null ? null : bchVmCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_CONT_USR
     *
     * @return the value of S_BCH.BCH_CONT_USR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchContUsr() {
        return bchContUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_CONT_USR
     *
     * @param bchContUsr the value for S_BCH.BCH_CONT_USR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchContUsr(String bchContUsr) {
        this.bchContUsr = bchContUsr == null ? null : bchContUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_CONT_TEL
     *
     * @return the value of S_BCH.BCH_CONT_TEL
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchContTel() {
        return bchContTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_CONT_TEL
     *
     * @param bchContTel the value for S_BCH.BCH_CONT_TEL
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchContTel(String bchContTel) {
        this.bchContTel = bchContTel == null ? null : bchContTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_ADDR
     *
     * @return the value of S_BCH.BCH_ADDR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchAddr() {
        return bchAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_ADDR
     *
     * @param bchAddr the value for S_BCH.BCH_ADDR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchAddr(String bchAddr) {
        this.bchAddr = bchAddr == null ? null : bchAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_ZIP
     *
     * @return the value of S_BCH.BCH_ZIP
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchZip() {
        return bchZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_ZIP
     *
     * @param bchZip the value for S_BCH.BCH_ZIP
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchZip(String bchZip) {
        this.bchZip = bchZip == null ? null : bchZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_TEMP_ACCT_NO
     *
     * @return the value of S_BCH.BCH_TEMP_ACCT_NO
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchTempAcctNo() {
        return bchTempAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_TEMP_ACCT_NO
     *
     * @param bchTempAcctNo the value for S_BCH.BCH_TEMP_ACCT_NO
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchTempAcctNo(String bchTempAcctNo) {
        this.bchTempAcctNo = bchTempAcctNo == null ? null : bchTempAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_STATUS
     *
     * @return the value of S_BCH.BCH_STATUS
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchStatus() {
        return bchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_STATUS
     *
     * @param bchStatus the value for S_BCH.BCH_STATUS
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchStatus(String bchStatus) {
        this.bchStatus = bchStatus == null ? null : bchStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.BCH_LOAN_IND
     *
     * @return the value of S_BCH.BCH_LOAN_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getBchLoanInd() {
        return bchLoanInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.BCH_LOAN_IND
     *
     * @param bchLoanInd the value for S_BCH.BCH_LOAN_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setBchLoanInd(String bchLoanInd) {
        this.bchLoanInd = bchLoanInd == null ? null : bchLoanInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.LAST_CHG_DT
     *
     * @return the value of S_BCH.LAST_CHG_DT
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getLastChgDt() {
        return lastChgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.LAST_CHG_DT
     *
     * @param lastChgDt the value for S_BCH.LAST_CHG_DT
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setLastChgDt(String lastChgDt) {
        this.lastChgDt = lastChgDt == null ? null : lastChgDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.LAST_CHG_USR
     *
     * @return the value of S_BCH.LAST_CHG_USR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getLastChgUsr() {
        return lastChgUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.LAST_CHG_USR
     *
     * @param lastChgUsr the value for S_BCH.LAST_CHG_USR
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setLastChgUsr(String lastChgUsr) {
        this.lastChgUsr = lastChgUsr == null ? null : lastChgUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.ZHXT_IND
     *
     * @return the value of S_BCH.ZHXT_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getZhxtInd() {
        return zhxtInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.ZHXT_IND
     *
     * @param zhxtInd the value for S_BCH.ZHXT_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setZhxtInd(String zhxtInd) {
        this.zhxtInd = zhxtInd == null ? null : zhxtInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_BCH.OL_IND
     *
     * @return the value of S_BCH.OL_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public String getOlInd() {
        return olInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_BCH.OL_IND
     *
     * @param olInd the value for S_BCH.OL_IND
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    public void setOlInd(String olInd) {
        this.olInd = olInd == null ? null : olInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_BCH
     *
     * @mbg.generated Wed Aug 08 17:56:59 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bchCde=").append(bchCde);
        sb.append(", bankCde=").append(bankCde);
        sb.append(", bchLegalCde=").append(bchLegalCde);
        sb.append(", bchDesc=").append(bchDesc);
        sb.append(", bchFincCde=").append(bchFincCde);
        sb.append(", bchLevel=").append(bchLevel);
        sb.append(", bchFarCde=").append(bchFarCde);
        sb.append(", bchAcctCde=").append(bchAcctCde);
        sb.append(", bchVmCde=").append(bchVmCde);
        sb.append(", bchContUsr=").append(bchContUsr);
        sb.append(", bchContTel=").append(bchContTel);
        sb.append(", bchAddr=").append(bchAddr);
        sb.append(", bchZip=").append(bchZip);
        sb.append(", bchTempAcctNo=").append(bchTempAcctNo);
        sb.append(", bchStatus=").append(bchStatus);
        sb.append(", bchLoanInd=").append(bchLoanInd);
        sb.append(", lastChgDt=").append(lastChgDt);
        sb.append(", lastChgUsr=").append(lastChgUsr);
        sb.append(", zhxtInd=").append(zhxtInd);
        sb.append(", olInd=").append(olInd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}