package com.zhen.base.domain.system;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.id
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * id
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.login_name
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * 登录用户名
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * 密码
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.user_name
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * 用户名
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.mobile
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * 手机号
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.email
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * 邮箱
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.create_time
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * 创建时间
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.create_user
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    /**
     * 创建用户
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_user
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.id
     *
     * @return the value of s_user.id
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.id
     *
     * @param id the value for s_user.id
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.login_name
     *
     * @return the value of s_user.login_name
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.login_name
     *
     * @param loginName the value for s_user.login_name
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.password
     *
     * @param password the value for s_user.password
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.user_name
     *
     * @return the value of s_user.user_name
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.user_name
     *
     * @param userName the value for s_user.user_name
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.mobile
     *
     * @return the value of s_user.mobile
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.mobile
     *
     * @param mobile the value for s_user.mobile
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.email
     *
     * @return the value of s_user.email
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.email
     *
     * @param email the value for s_user.email
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.create_time
     *
     * @return the value of s_user.create_time
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.create_time
     *
     * @param createTime the value for s_user.create_time
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.create_user
     *
     * @return the value of s_user.create_user
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.create_user
     *
     * @param createUser the value for s_user.create_user
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Thu Sep 13 22:13:06 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", password=").append(password);
        sb.append(", userName=").append(userName);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}